version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - mvn clean package
  post_build:
    commands:
      - echo "Build successful"
artifacts:
  files:
    - target/*.jar
  discard-paths: yes

